import type { ImageSourcePropType } from 'react-native';

/** Generated by scripts/food-images.py. Small photo per food; foods not listed fall back to a pictogram. */
export const FOOD_IMAGES: Record<string, ImageSourcePropType> = {};
