import type { ImageSourcePropType } from 'react-native';

/** Generated by scripts/yoga-images.py. One instructional photo per asana. */
export const YOGA_IMAGES: Record<string, ImageSourcePropType> = {
  'adho-mukha': require('../../assets/yoga/adho-mukha.webp'),
  'anulom-vilom': require('../../assets/yoga/anulom-vilom.webp'),
  'ardha-matsyendrasana': require('../../assets/yoga/ardha-matsyendrasana.webp'),
  'balasana': require('../../assets/yoga/balasana.webp'),
  'bhramari': require('../../assets/yoga/bhramari.webp'),
  'bhujangasana': require('../../assets/yoga/bhujangasana.webp'),
  'kapalbhati': require('../../assets/yoga/kapalbhati.webp'),
  'marjariasana': require('../../assets/yoga/marjariasana.webp'),
  'naukasana': require('../../assets/yoga/naukasana.webp'),
  'paschimottanasana': require('../../assets/yoga/paschimottanasana.webp'),
  'pawanmuktasana': require('../../assets/yoga/pawanmuktasana.webp'),
  'setu-bandhasana': require('../../assets/yoga/setu-bandhasana.webp'),
  'shalabhasana': require('../../assets/yoga/shalabhasana.webp'),
  'shavasana': require('../../assets/yoga/shavasana.webp'),
  'surya-namaskar': require('../../assets/yoga/surya-namaskar.webp'),
  'tadasana': require('../../assets/yoga/tadasana.webp'),
  'trikonasana': require('../../assets/yoga/trikonasana.webp'),
  'utkatasana': require('../../assets/yoga/utkatasana.webp'),
  'vajrasana': require('../../assets/yoga/vajrasana.webp'),
  'vrikshasana': require('../../assets/yoga/vrikshasana.webp'),
};
